# Generated by Django 3.2.16 on 2023-04-26 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0085_alter_resourcebase_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemotePushSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('ended', models.DateTimeField(blank=True, editable=False, null=True)),
                ('details', models.TextField(blank=True, editable=False)),
                ('force', models.BooleanField(default=False, editable=False)),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('RUNNING', 'running'), ('SUCCESS', 'success'), ('FAILURE', 'failure'), ('ABORTING', 'aborting'), ('ABORTED', 'aborted'), ('PARTIAL_FAILURE', 'partial failure')], default='PENDING', editable=False, max_length=50)),
                ('total_resources_to_process', models.IntegerField(default=0, editable=False, help_text='Number of resources being processed in this session')),
                ('resources_done', models.IntegerField(default=0, help_text='Number of resources that have already been processed')),
                ('initiator', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('remote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sync.remotegeonodeinstance')),
            ],
        ),
        migrations.CreateModel(
            name='RemotePushJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('RUNNING', 'running'), ('SUCCESS', 'success'), ('FAILURE', 'failure'), ('ABORTED', 'aborted')], default='PENDING', editable=False, max_length=50)),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('ended', models.DateTimeField(blank=True, null=True)),
                ('details', models.TextField(blank=True)),
                ('resource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.resourcebase')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sync.remotepushsession')),
            ],
        ),
    ]
