# Generated by Django 3.2.16 on 2023-04-27 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sync', '0002_remotepushjob_remotepushsession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remotepushjob',
            options={'verbose_name': 'Remote Push Job'},
        ),
        migrations.AlterModelOptions(
            name='remotepushsession',
            options={'verbose_name': 'Remote Push Session'},
        ),
        migrations.AlterField(
            model_name='remotepushjob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('RUNNING', 'running'), ('SUCCESS', 'success'), ('FAILURE', 'failure'), ('ABORTING', 'aborting'), ('ABORTED', 'aborted')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='remotepushsession',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='remotepushsession',
            name='ended',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='remotepushsession',
            name='force',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='remotepushsession',
            name='initiator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='remotepushsession',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('RUNNING', 'running'), ('SUCCESS', 'success'), ('FAILURE', 'failure'), ('ABORTING', 'aborting'), ('ABORTED', 'aborted'), ('PARTIAL_FAILURE', 'partial failure')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='remotepushsession',
            name='total_resources_to_process',
            field=models.IntegerField(default=0, help_text='Number of resources being processed in this session'),
        ),
    ]
