# Generated by Django 3.2.16 on 2022-10-27 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geoapps', '0006_geoapp_blob_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonSpatialDataset',
            fields=[
                ('resourcebase_ptr', models.OneToOneField(parent_link=True, on_delete=models.CASCADE,
                                                          auto_created=True, primary_key=True, serialize=False, to='base.ResourceBase')),
                ('postgres_url', models.URLField(help_text='Link to the dataset', max_length=2000, null=True, blank=True)),
                ('database_table', models.CharField(max_length=255, null=True, blank=True)),
                ('column_definitions', models.TextField(help_text='brief narrative summary of the content of the resource(s)')),
                
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('base.resourcebase',),
        ),
    ]

